# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 03:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationInfoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_number', models.CharField(max_length=30)),
                ('paid', models.BooleanField(default=False)),
                ('subject', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='register.ExamInfoModel')),
            ],
        ),
    ]
