# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 13:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceModel',
            fields=[
                ('place', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='考试地点')),
            ],
        ),
        migrations.AlterField(
            model_name='examinfomodel',
            name='exam_time_end',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='考试结束时间'),
        ),
    ]
