# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 07:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_student'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='StudentInfoModel',
        ),
    ]
