# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 10:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_auto_20160414_2359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationinfomodel',
            name='subject',
        ),
        migrations.RenameField(
            model_name='examinfomodel',
            old_name='time',
            new_name='exam_time',
        ),
        migrations.AddField(
            model_name='examinfomodel',
            name='register_deadline',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterUniqueTogether(
            name='examinfomodel',
            unique_together=set([('subject', 'exam_time', 'place')]),
        ),
        migrations.DeleteModel(
            name='RegistrationInfoModel',
        ),
    ]
