# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 01:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_auto_20160418_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='examinfomodel',
            name='exam_time_end',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 19, 1, 7, 46, 763135, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='examinfomodel',
            name='notes',
            field=models.CharField(default='', max_length=512),
        ),
    ]
