# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 01:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0009_auto_20160419_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examinfomodel',
            name='exam_time_end',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 19, 1, 15, 54, 889495, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='examinfomodel',
            name='subject',
            field=models.CharField(max_length=30, verbose_name='科目名称'),
        ),
    ]
