# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 15:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_registrationinfomodel_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationinfomodel',
            name='place',
            field=models.ForeignKey(default='25#324', on_delete=django.db.models.deletion.CASCADE, to='register.PlaceModel'),
        ),
    ]
