# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 10:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_auto_20160418_1850'),
        ('accounts', '0002_auto_20160416_0216'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationInfoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_number', models.CharField(max_length=30)),
                ('is_paid', models.BooleanField(default=False)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.ExamInfoModel')),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registrationinfomodel',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Student'),
        ),
        migrations.AddField(
            model_name='student',
            name='exam',
            field=models.ManyToManyField(through='accounts.RegistrationInfoModel', to='register.ExamInfoModel'),
        ),
    ]
