# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_student_head_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationinfomodel',
            name='exam_number',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='head_image',
            field=models.ImageField(default='images/fuckFu.jpg', upload_to='images/'),
        ),
    ]
